//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Dfdf
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Согласие.
    /// </summary>
    // *** Start programmer edit section *** (Согласие CustomAttributes)

    // *** End programmer edit section *** (Согласие CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СогласиеE", new string[] {
            "Код as \'Код\'",
            "Дата as \'Дата\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.Фио as \'Фио\'"}, Hidden=new string[] {
            "Сотрудники.Фио"})]
    [MasterViewDefineAttribute("СогласиеE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фио")]
    [View("СогласиеL", new string[] {
            "Код as \'Код\'",
            "Дата as \'Дата\'",
            "Сотрудники.Фио as \'Фио\'"})]
    public class Согласие : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private System.DateTime fДата;
        
        private IIS.Dfdf.ДирПерсонала fДирПерсонала;
        
        private IIS.Dfdf.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (Согласие CustomMembers)

        // *** End programmer edit section *** (Согласие CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Согласие.Дата CustomAttributes)

        // *** End programmer edit section *** (Согласие.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Согласие.Дата Get start)

                // *** End programmer edit section *** (Согласие.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Согласие.Дата Get end)

                // *** End programmer edit section *** (Согласие.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Согласие.Дата Set start)

                // *** End programmer edit section *** (Согласие.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Согласие.Дата Set end)

                // *** End programmer edit section *** (Согласие.Дата Set end)
            }
        }
        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (Согласие.Код CustomAttributes)

        // *** End programmer edit section *** (Согласие.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (Согласие.Код Get start)

                // *** End programmer edit section *** (Согласие.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (Согласие.Код Get end)

                // *** End programmer edit section *** (Согласие.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Согласие.Код Set start)

                // *** End programmer edit section *** (Согласие.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (Согласие.Код Set end)

                // *** End programmer edit section *** (Согласие.Код Set end)
            }
        }
        
        /// <summary>
        /// Согласие.
        /// </summary>
        // *** Start programmer edit section *** (Согласие.ДирПерсонала CustomAttributes)

        // *** End programmer edit section *** (Согласие.ДирПерсонала CustomAttributes)
        [PropertyStorage(new string[] {
                "ДирПерсонала"})]
        [NotNull()]
        public virtual IIS.Dfdf.ДирПерсонала ДирПерсонала
        {
            get
            {
                // *** Start programmer edit section *** (Согласие.ДирПерсонала Get start)

                // *** End programmer edit section *** (Согласие.ДирПерсонала Get start)
                IIS.Dfdf.ДирПерсонала result = this.fДирПерсонала;
                // *** Start programmer edit section *** (Согласие.ДирПерсонала Get end)

                // *** End programmer edit section *** (Согласие.ДирПерсонала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Согласие.ДирПерсонала Set start)

                // *** End programmer edit section *** (Согласие.ДирПерсонала Set start)
                this.fДирПерсонала = value;
                // *** Start programmer edit section *** (Согласие.ДирПерсонала Set end)

                // *** End programmer edit section *** (Согласие.ДирПерсонала Set end)
            }
        }
        
        /// <summary>
        /// Согласие.
        /// </summary>
        // *** Start programmer edit section *** (Согласие.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (Согласие.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Dfdf.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (Согласие.Сотрудники Get start)

                // *** End programmer edit section *** (Согласие.Сотрудники Get start)
                IIS.Dfdf.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (Согласие.Сотрудники Get end)

                // *** End programmer edit section *** (Согласие.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Согласие.Сотрудники Set start)

                // *** End programmer edit section *** (Согласие.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (Согласие.Сотрудники Set end)

                // *** End programmer edit section *** (Согласие.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СогласиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СогласиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СогласиеE", typeof(IIS.Dfdf.Согласие));
                }
            }
            
            /// <summary>
            /// "СогласиеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СогласиеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СогласиеL", typeof(IIS.Dfdf.Согласие));
                }
            }
        }
    }
}
